---
- src: dev-sec.ssh-hardening
- src: geerlingguy.ntp
- src: ivoamorim.iptables
- src: ivoamorim.logrotate
- src: ivoamorim.packages
- src: ivoamorim.package_utilities
- src: ivoamorim.selinux
- src: ivoamorim.syslog
- src: oefenweb.fail2ban
