---
- src: dev-sec.ssh-hardening
- src: geerlingguy.ntp
- src: ivoamorim.iptables
- src: ivoamorim.logrotate
- src: ivoamorim.package_utilities
- src: ivoamorim.selinux
- src: ivoamorim.sysadmin
- src: ivoamorim.syslog
- src: ivoamorim.tcpwrappers
- src: linuxhq.sysctl
